/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityCodeRouteImport } from './routes/community-code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PartnerIdRouteImport } from './routes/partner/$id'
import { Route as ModeratorFlagsRouteImport } from './routes/moderator/flags'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminAlumniRouteImport } from './routes/admin/alumni'
import { Route as ModeratorFlagsFlagIdRouteImport } from './routes/moderator/flags.$flagId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCodeRoute = CommunityCodeRouteImport.update({
  id: '/community-code',
  path: '/community-code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIdRoute = PartnerIdRouteImport.update({
  id: '/partner/$id',
  path: '/partner/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorFlagsRoute = ModeratorFlagsRouteImport.update({
  id: '/moderator/flags',
  path: '/moderator/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlumniRoute = AdminAlumniRouteImport.update({
  id: '/admin/alumni',
  path: '/admin/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorFlagsFlagIdRoute = ModeratorFlagsFlagIdRouteImport.update({
  id: '/$flagId',
  path: '/$flagId',
  getParentRoute: () => ModeratorFlagsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-code': typeof CommunityCodeRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/success': typeof SuccessRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/admin/alumni': typeof AdminAlumniRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/flags': typeof ModeratorFlagsRouteWithChildren
  '/partner/$id': typeof PartnerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/flags/$flagId': typeof ModeratorFlagsFlagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-code': typeof CommunityCodeRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/success': typeof SuccessRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/admin/alumni': typeof AdminAlumniRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/flags': typeof ModeratorFlagsRouteWithChildren
  '/partner/$id': typeof PartnerIdRoute
  '/admin': typeof AdminIndexRoute
  '/moderator/flags/$flagId': typeof ModeratorFlagsFlagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-code': typeof CommunityCodeRoute
  '/dashboard': typeof DashboardRoute
  '/delete-account': typeof DeleteAccountRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/success': typeof SuccessRoute
  '/suggestions': typeof SuggestionsRoute
  '/terms': typeof TermsRoute
  '/admin/alumni': typeof AdminAlumniRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/flags': typeof ModeratorFlagsRouteWithChildren
  '/partner/$id': typeof PartnerIdRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/flags/$flagId': typeof ModeratorFlagsFlagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-code'
    | '/dashboard'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/success'
    | '/suggestions'
    | '/terms'
    | '/admin/alumni'
    | '/admin/locations'
    | '/admin/reports'
    | '/admin/users'
    | '/moderator/flags'
    | '/partner/$id'
    | '/admin/'
    | '/moderator/flags/$flagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-code'
    | '/dashboard'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/success'
    | '/suggestions'
    | '/terms'
    | '/admin/alumni'
    | '/admin/locations'
    | '/admin/reports'
    | '/admin/users'
    | '/moderator/flags'
    | '/partner/$id'
    | '/admin'
    | '/moderator/flags/$flagId'
  id:
    | '__root__'
    | '/'
    | '/community-code'
    | '/dashboard'
    | '/delete-account'
    | '/login'
    | '/privacy'
    | '/success'
    | '/suggestions'
    | '/terms'
    | '/admin/alumni'
    | '/admin/locations'
    | '/admin/reports'
    | '/admin/users'
    | '/moderator/flags'
    | '/partner/$id'
    | '/admin/'
    | '/moderator/flags/$flagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityCodeRoute: typeof CommunityCodeRoute
  DashboardRoute: typeof DashboardRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SuccessRoute: typeof SuccessRoute
  SuggestionsRoute: typeof SuggestionsRoute
  TermsRoute: typeof TermsRoute
  AdminAlumniRoute: typeof AdminAlumniRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ModeratorFlagsRoute: typeof ModeratorFlagsRouteWithChildren
  PartnerIdRoute: typeof PartnerIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-code': {
      id: '/community-code'
      path: '/community-code'
      fullPath: '/community-code'
      preLoaderRoute: typeof CommunityCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/$id': {
      id: '/partner/$id'
      path: '/partner/$id'
      fullPath: '/partner/$id'
      preLoaderRoute: typeof PartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/flags': {
      id: '/moderator/flags'
      path: '/moderator/flags'
      fullPath: '/moderator/flags'
      preLoaderRoute: typeof ModeratorFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alumni': {
      id: '/admin/alumni'
      path: '/admin/alumni'
      fullPath: '/admin/alumni'
      preLoaderRoute: typeof AdminAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/flags/$flagId': {
      id: '/moderator/flags/$flagId'
      path: '/$flagId'
      fullPath: '/moderator/flags/$flagId'
      preLoaderRoute: typeof ModeratorFlagsFlagIdRouteImport
      parentRoute: typeof ModeratorFlagsRoute
    }
  }
}

interface ModeratorFlagsRouteChildren {
  ModeratorFlagsFlagIdRoute: typeof ModeratorFlagsFlagIdRoute
}

const ModeratorFlagsRouteChildren: ModeratorFlagsRouteChildren = {
  ModeratorFlagsFlagIdRoute: ModeratorFlagsFlagIdRoute,
}

const ModeratorFlagsRouteWithChildren = ModeratorFlagsRoute._addFileChildren(
  ModeratorFlagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityCodeRoute: CommunityCodeRoute,
  DashboardRoute: DashboardRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SuccessRoute: SuccessRoute,
  SuggestionsRoute: SuggestionsRoute,
  TermsRoute: TermsRoute,
  AdminAlumniRoute: AdminAlumniRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ModeratorFlagsRoute: ModeratorFlagsRouteWithChildren,
  PartnerIdRoute: PartnerIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
