/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIdRouteImport } from './routes/partner/$id'
import { Route as ModeratorFlagsRouteImport } from './routes/moderator/flags'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as ModeratorFlagsFlagIdRouteImport } from './routes/moderator/flags.$flagId'

const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIdRoute = PartnerIdRouteImport.update({
  id: '/partner/$id',
  path: '/partner/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorFlagsRoute = ModeratorFlagsRouteImport.update({
  id: '/moderator/flags',
  path: '/moderator/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorFlagsFlagIdRoute = ModeratorFlagsFlagIdRouteImport.update({
  id: '/$flagId',
  path: '/$flagId',
  getParentRoute: () => ModeratorFlagsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/suggestions': typeof SuggestionsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/moderator/flags': typeof ModeratorFlagsRouteWithChildren
  '/partner/$id': typeof PartnerIdRoute
  '/moderator/flags/$flagId': typeof ModeratorFlagsFlagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/suggestions': typeof SuggestionsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/moderator/flags': typeof ModeratorFlagsRouteWithChildren
  '/partner/$id': typeof PartnerIdRoute
  '/moderator/flags/$flagId': typeof ModeratorFlagsFlagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/suggestions': typeof SuggestionsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/moderator/flags': typeof ModeratorFlagsRouteWithChildren
  '/partner/$id': typeof PartnerIdRoute
  '/moderator/flags/$flagId': typeof ModeratorFlagsFlagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/suggestions'
    | '/admin/locations'
    | '/moderator/flags'
    | '/partner/$id'
    | '/moderator/flags/$flagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/suggestions'
    | '/admin/locations'
    | '/moderator/flags'
    | '/partner/$id'
    | '/moderator/flags/$flagId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/suggestions'
    | '/admin/locations'
    | '/moderator/flags'
    | '/partner/$id'
    | '/moderator/flags/$flagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  SuggestionsRoute: typeof SuggestionsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  ModeratorFlagsRoute: typeof ModeratorFlagsRouteWithChildren
  PartnerIdRoute: typeof PartnerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/$id': {
      id: '/partner/$id'
      path: '/partner/$id'
      fullPath: '/partner/$id'
      preLoaderRoute: typeof PartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/flags': {
      id: '/moderator/flags'
      path: '/moderator/flags'
      fullPath: '/moderator/flags'
      preLoaderRoute: typeof ModeratorFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/flags/$flagId': {
      id: '/moderator/flags/$flagId'
      path: '/$flagId'
      fullPath: '/moderator/flags/$flagId'
      preLoaderRoute: typeof ModeratorFlagsFlagIdRouteImport
      parentRoute: typeof ModeratorFlagsRoute
    }
  }
}

interface ModeratorFlagsRouteChildren {
  ModeratorFlagsFlagIdRoute: typeof ModeratorFlagsFlagIdRoute
}

const ModeratorFlagsRouteChildren: ModeratorFlagsRouteChildren = {
  ModeratorFlagsFlagIdRoute: ModeratorFlagsFlagIdRoute,
}

const ModeratorFlagsRouteWithChildren = ModeratorFlagsRoute._addFileChildren(
  ModeratorFlagsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  SuggestionsRoute: SuggestionsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  ModeratorFlagsRoute: ModeratorFlagsRouteWithChildren,
  PartnerIdRoute: PartnerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
